/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f190a7dd-a11a-41c5-a2c1-bdf16b23f5f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MTqMj27Jp",
    "aws_user_pools_web_client_id": "1rl3o84j4e6iom9vpu11vf4vuj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://r2ksjxmztvg7fnpzwfelwfsfse.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3e63l5cce5geree46d4fajdfia"
};


export default awsmobile;
